# @copyright &copy; 2010 - 2017, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. All rights reserved.
#
# BSD 3-Clause License
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
# 1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# 2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
# 3.  Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to foxBMS in your hardware, software, documentation or advertising materials:
#
# &Prime;This product uses parts of foxBMS&reg;&Prime;
#
# &Prime;This product includes parts of foxBMS&reg;&Prime;
#
# &Prime;This product is derived from foxBMS&reg;&Prime;

"""WAF script for building "foxbms-application" library.
location of this wscript:
    /src/application/wscript

library output:
    /build/src/application/libfoxbms-application.a

"""

from waflib import Logs, Utils, Context
import os


def build(bld):
    srcs = bld.path.ant_glob('**/*.c')

    includes = os.path.join(bld.bldnode.abspath()) + ' '
    includes += ' '.join([
            '.',
            

            os.path.join('bal'),
            os.path.join('bmsctrl'),
            os.path.join('com'),
            os.path.join('config'),
            os.path.join('sox'),
            os.path.join('task'),
            
            os.path.join('..', 'engine', 'config'),
            os.path.join('..', 'engine', 'database'),
            os.path.join('..', 'engine', 'diag'),
            os.path.join('..', 'engine', 'sysctrl'),

            os.path.join('..', 'general'),
            os.path.join('..', 'general', 'config'),
            os.path.join('..', 'general', 'includes'),

            os.path.join(bld.top_dir, 'hal', 'CMSIS', 'Device', 'ST', 'STM32F4xx', 'Include'),
            os.path.join(bld.top_dir, 'hal', 'CMSIS', 'Include'),
            os.path.join(bld.top_dir, 'hal', 'STM32F4xx_HAL_Driver', 'Inc'),
            os.path.join(bld.top_dir, 'hal', 'STM32F4xx_HAL_Driver', 'Inc', 'Legacy'),

            os.path.join('..', 'module', 'can'),
            os.path.join('..', 'module', 'cansignal'),
            os.path.join('..', 'module', 'config'),
            os.path.join('..', 'module', 'contactor'),
            os.path.join('..', 'module', 'nvram'),
            os.path.join('..', 'module', 'io'),
            os.path.join('..', 'module', 'mcu'),
            os.path.join('..', 'module', 'rtc'),
            os.path.join('..', 'module', 'uart'),
            os.path.join('..', 'module', 'utils'),

            os.path.join('..', 'os'),
            os.path.join(bld.top_dir, 'FreeRTOS', 'Source', 'CMSIS_RTOS'),
            os.path.join(bld.top_dir, 'FreeRTOS', 'Source', 'include'),
            os.path.join(bld.top_dir, 'FreeRTOS', 'Source', 'portable', 'GCC', 'ARM_CM4F'),
            ])


    bld.stlib(
              target='foxbms-application',
              source=srcs,
              includes=includes
              )

# vim: set ft=python :
